version: '3'
services:
  mongodb:
    image: mongo
    ports:
    - 27017:27017
  reddit_collector:
    build: reddit_collector/
    volumes:
    - ./reddit_collector/:/app
    depends_on:
    - mongodb
  postgresdb:
    image: postgres
    ports:
    - 5555:5432
    environment:
    - POSTGRES_USER=value
    - POSTGRES_PASSWORD=1234
    - POSTGRES_DB=reddit    
  etl_job:
    build: etl_job/
    volumes:
    - ./etl_job/:/app
    depends_on:
    - mongodb
    - postgresdb

  slackbot:
    build: slackbot/
    volumes:
    - ./slackbot/:/app
    depends_on:
    - postgresdb
     
    
  




 

 # 

